import Head from 'next/head'
import Navbar from '@/components/Navbar'
import Header from '@/components/Header'
import Services from '@/components/Services'
import Porfolio from '@/components/Porfolio'
import Team from '@/components/Team'
import Clients from '@/components/Clients'
import Contact from '@/components/Contact'
import Footer from '@/components/Footer'
import About from '@/components/About'
import { Button } from 'react-bootstrap'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     
      <Navbar/>
      <Header/>    
      <Services/>
      <Porfolio />
      <About/>
      <Team/>
      <Clients/>
      <Contact />
      <Footer/>
    </>
  )
}
